PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dbp: <http://dbpedia.org/ontology/>
PREFIX bgh: <http://data.businessgraph.io/>
PREFIX schema: <http://schema.org/>

SELECT ?qlegalname ?qstreet ?qpostalcode ?qlocality ?qcountry ?qname ?qemail ?qtelephone ?qurl ?qfax
WHERE {
  ?id a ocds:Organisation .
  ?id ocds:isBuyerFor ?id .
  ?id ocds:legalName ?qlegalname .
  OPTIONAL { ?id ocds:hasAddress ?haddress .
            OPTIONAL { ?haddress schema:streetAddress ?qstreet .
                       ?haddress schema:postalCode ?qpostalcode .
                       ?haddress schema:addressLocality ?qlocality .
                       ?haddress schema:addressCountry ?qcountry }} .
  OPTIONAL { ?id ocds:hasContactPoint ?hcp .
            OPTIONAL { ?hcp schema:name ?qname .
                       ?hcp schema:email ?qemail .
                       ?hcp schema:telephone ?qtelephone .
                       OPTIONAL { ?hcp schema:URL ?qurl .
                                  ?hcp schema:faxNumber ?qfax }}} .
# So far, no buyer has correspondance with euBG
#  OPTIONAL { ?id owl:sameAs ?idas .
#  OPTIONAL { ?idas regorg:legalName ?qname .
#             ?idas dbp:jurisdiction ?qjurisdiction }} .
}
