PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dbp: <http://dbpedia.org/ontology/>
PREFIX bgh: <http://data.businessgraph.io/>
PREFIX schema: <http://schema.org/>

SELECT ?s ?sas ?qname ?qjurisdiction
WHERE {
  ?s a ocds:Organisation .
  ?s ocds:isBuyerFor ?id .
  OPTIONAL { ?s owl:sameAs ?sas .
  OPTIONAL { ?sas regorg:legalName ?qname .
             ?sas dbp:jurisdiction ?qjurisdiction }} .
}
