PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tbfy: <https://theybuyforyou.eu/ontology/ocds/>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT (?id as ?oid) ?isf ?dat ?tit
WHERE {
	?id a tbfy:ContractingProcess .
  ?id tbfy:hasAward ?isf .
  ?isf a tbfy:Award .
  ?isf tbfy:awardDate ?dat .
	OPTIONAL { ?s dcterms:title ?tit } .
}
