PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX tbfy: <http://data.tbfy.eu/ontology/tbfy#>

SELECT (?id as ?oid) ?pri ?releasepublisheddate
WHERE {
	?id a ocds:Tender .
  ?pri a ocds:ContractingProcess .
	?pri ocds:hasTender ?id .
	?pri ocds:hasRelease ?hasrelease .
	?hasrelease tbfy:releasePublishedDate ?releasepublisheddate .
}
