PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tbfy: <http://data.tbfy.eu/ontology/ocds/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>
SELECT (?id as ?oid) ?tit ?doc ?lan ?url ?type
WHERE {
	?id a tbfy:Award .
  OPTIONAL { ?id dcterms:title ?tit } .
  ?id tbfy:hasDocument ?doc .
	OPTIONAL { ?doc dcterms:language ?lan } .
  OPTIONAL { ?doc schema:URL ?url } .
	OPTIONAL { ?doc tbfy:documentType ?type } .
}
