PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>

SELECT (?id as ?oid) ?itm ?enq ?cl1 ?cl2
WHERE {
	?id a ocds:Contract .
  ?id ocds:hasContractedItem ?itm .
	OPTIONAL { ?itm ocds:hasRelatedEnquiry ?enq } .
	OPTIONAL { ?itm ocds:classificatonScheme ?cl1 } .
  OPTIONAL { ?itm ocds:hasClassificaton ?cl2 } .
}
