PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT (?id as ?oid) ?ibf ?hn
WHERE {
	?id a ocds:Contract .
  OPTIONAL { ?id dct:title ?tit } .
  ?id ocds:isBuyerFor ?ibf .
	OPTIONAL { ?ibf a ocds:Organisation } .
  OPTIONAL { ?ibf ocds:legalName ?hn } .
}
