PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tbfy: <https://theybuyforyou.eu/ontology/ocds/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>
SELECT DISTINCT (?id as ?oid) ?dat ?tit ?isf ?stat
WHERE {
	?id a tbfy:Organisation .
  ?id tbfy:isSupplierFor ?isf .
  ?isf a tbfy:Award .
  OPTIONAL { ?isf tbfy:awardDate ?dat } .
  OPTIONAL { ?isf dcterms:title ?tit } .
  OPTIONAL { ?isf dcterms:description ?des } .
  OPTIONAL { ?isf tbfy:awardStatus ?stat } .
}
