PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX tbfy: <http://data.tbfy.eu/ontology/tbfy#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?qid ?releasepublisheddate ?qclassification
WHERE {
		?qid a ocds:ContractingProcess .
		?qid ocds:hasRelease ?hasrelease .
 		?hasrelease tbfy:releasePublishedDate ?releasepublisheddate .
		?qid ocds:hasTender ?tender .
		?tender ocds:hasItemToBeProcured ?item .
		OPTIONAL { ?item ocds:classificationScheme ?qclassificationscheme ;
							       ocds:hasClassificaton ?qclassification } .
		OPTIONAL { ?qid ocds:additionalItemClassificationScheme ?qadditclassificationscheme ;
									  ocds:hasAdditionalItemClassificaton ?qadditclassification } .
		FILTER ( ?code = xsd:string("_empty_") || regex( ?qclassification, str(?code), "i") ) .
		FILTER ( ?start_dt = xsd:string("_empty_") || ?releasepublisheddate > ?start_dt ) .
		FILTER ( ?end_dt = xsd:string("_empty_") || ?releasepublisheddate < ?end_dt ) .
}
