PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT ?qid ?hasdocid ?hasdoctype ?hasdoclan ?hasdocurl
WHERE {
?qid a ocds:ContractingProcess .

#Object Property hasPlan
OPTIONAL { ?qid ocds:hasPlan ?plan } .
OPTIONAL { ?plan ocds:hasDocument ?hasdoc } .
OPTIONAL { ?hasdoc ocds:documentId ?hasdocid } .
OPTIONAL { ?hasdoc ocds:documentType ?hasdoctype } .
OPTIONAL { ?hasdoc dct:language ?hasdoclan } .
OPTIONAL { ?hasdoc schema:URL ?hasdocurl } .

}
