PREFIX rov: <http://www.w3.org/ns/regorg#>
PREFIX dbp: <http://dbpedia.org/ontology/>

SELECT ?s ?qlegalname ?qjurisdiction WHERE {
  ?s a rov:RegisteredOrganization .
  ?s rov:legalName ?qlegalname .
  ?s dbp:jurisdiction ?qjurisdiction .
  FILTER ( ?name = xsd:string("_empty_") || regex( ?qlegalname, ?name, "i") ) .
  FILTER ( ?jurisdiction = xsd:string("_empty_") || regex( ?qjurisdiction, ?jurisdiction, "i" ) ) .
}
