PREFIX org: <http://www.w3.org/ns/org#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX schema: <http://schema.org/>
PREFIX dbp: <http://dbpedia.org/ontology/>
PREFIX rov: <http://www.w3.org/ns/regorg#>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX ebg: <http://data.businessgraph.io/ontology#>

SELECT ( ?id as ?oid ) ?qlegalname ?qjurisdiction ?qfoundingdate ?qdissolutiondate ?qnofemployees
?qactivitytext ?qstatustext ?qidentifier ?qtypetext ?qfulladdress ?qpostcode ?qpostname ?qthoroughfare ?qadminUnitL1
WHERE {

#Organisation information
  ?id a rov:RegisteredOrganization ;
      rov:legalName ?qlegalname ;
      dbp:jurisdiction ?qjurisdiction ;
      schema:foundingDate ?qfoundingdate ;
      schema:dissolutionDate ?qdissolutiondate ;
      ebg:numberOfEmployees ?qnofemployees ;
      ebg:orgActivityText ?qactivitytext ;
      ebg:orgStatusText ?qstatustext ;
      ebg:orgTypeText ?qtypetext .

#Object Property hasSite and hasRegisteredSite (both are the same)
  ?id rov:hasSite ?qhassite .
  ?qhassite org:siteAddress ?qsiteaddress ;
           locn:fullAddress ?qfulladdress ;
           locn:postCode ?qpostcode ;
           locn:postName ?qpostname ;
           locn:thoroughfare ?qthoroughfare ;

}
