PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tbfy: <https://theybuyforyou.eu/ontology/ocds/>
PREFIX schema: <http://schema.org/>
SELECT DISTINCT ( ?id as ?oid ) ?ln ?sad ?loc ?adc ?reg ?cp ?url ?eml ?tel ?adl
WHERE {
  ?id a tbfy:Organisation .
  OPTIONAL { ?id tbfy:legalName ?ln } .
  ?id tbfy:hasAddress ?adr .
  OPTIONAL { ?adr schema:streetAddress ?sad } .
  OPTIONAL { ?adr schema:addressLocality ?loc } .
  OPTIONAL { ?adr schema:addressCounty ?adc } .
  OPTIONAL { ?adr schema:region ?reg } .
  OPTIONAL { ?adr schema:postalCode ?cp } .
  ?id tbfy:hasContactPoint ?hcp .
  OPTIONAL { ?hcp schema:URL ?url } .
  OPTIONAL { ?hcp schema:email ?eml } .
  OPTIONAL { ?hcp schema:telephone ?tel } .
  OPTIONAL { ?hcp schema:addressLocality ?adl } .
}
