PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>

SELECT ?qid ?qstartdate ?qenddate
WHERE {
	?qid a ocds:Contract .
	?qid ocds:hasContractPeriod ?hcp .
  OPTIONAL { ?hcp ocds:periodStartDate ?qstartdate .
						 ?hcp ocds:periodEndDate ?qenddate } .
}
