PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tbfy: <https://theybuyforyou.eu/ontology/ocds/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>
SELECT DISTINCT ?s ?stat ?dcs ?impl ?period ?val ?milestone ?item ?award
WHERE {
	?s a tbfy:Contract .
  OPTIONAL { ?s tbfy:contractStatus ?stat } .
  OPTIONAL { ?s tbfy:dateContractSigned ?dcs } .
  OPTIONAL { ?s tbfy:hasContractImplementation ?impl } .
  OPTIONAL { ?s tbfy:hasContractPeriod ?period } .
  OPTIONAL { ?s tbfy:hasContractValue ?val } .
  OPTIONAL { ?s tbfy:hasMilestone ?milestone } .
  OPTIONAL { ?s tbfy:hasContractedItem ?item } .
  OPTIONAL { ?s tbfy:isIssuedForAward ?award }

}
