PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>

SELECT ( ?id AS ?oid ) ?qstartdate ?qenddate
WHERE {
	?id a ocds:Contract .
	?id ocds:hasContractPeriod ?hcp .
  OPTIONAL { ?hcp ocds:periodStartDate ?qstartdate .
		?hcp ocds:periodEndDate ?qenddate } .
}
