PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT ?qid ?qtitle ?qdescription ?qstatus
WHERE {
	?qid a ocds:Tender .
	OPTIONAL { ?qid dct:title ?qtitle } .
	OPTIONAL { ?qid dct:description ?qdescription } .
	OPTIONAL { ?qid ocds:tenderStatus ?qstatus } .
  FILTER ( regex(?qstatus, ?status, "i") || !isLiteral(?status) ) .
  FILTER ( regex(?qtitle, ?qtitlele, "i") || !isLiteral(?title) ) .
  FILTER ( regex(?qdescription, ?description, "i") || !isLiteral(?description) ) .
}
