PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?qid ?qtitle ?qdescription ?qstatus
WHERE {
	?qid a ocds:Tender .
	OPTIONAL { ?qid dct:title ?qtitle } .
	OPTIONAL { ?qid dct:description ?qdescription } .
	OPTIONAL { ?qid ocds:tenderStatus ?qstatus } .
	FILTER ( ?status = xsd:string("_empty_") || regex( ?status, ?status, "i") ) .
  FILTER ( ?title = xsd:string("_empty_") || regex( ?title, ?title, "i") ) .
  FILTER ( ?description = xsd:string("_empty_") || regex( ?description, ?description, "i") ) .
}
