PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tbfy: <https://theybuyforyou.eu/ontology/ocds/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>
SELECT DISTINCT ( ?id AS ?oid ) ?des ?stat ?mev ?minval ?maev ?maxval
WHERE {
  ?id a tbfy:Tender .
  ?id dcterms:description ?des .
  ?id tbfy:tenderStatus ?stat .
  ?id tbfy:hasMinEstimatedValue ?mev .
  OPTIONAL { ?mev rdf:minValue ?minval } .
  ?id tbfy:hasMaxEstimatedValue ?maev .
  OPTIONAL { ?maev rdf:value ?maxval } .
}
