PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>
SELECT ( ?id AS ?oid ) ?tenderid ?tendertitle ?tenderdescription ?tenderstatus ?hasdocid ?hasdoctype ?hasdoclan ?hasdocurl ?henq ?henqpstart ?henqpend ?hitbpid ?hitbpdes ?hitbpaic ?hitbphc ?hitbpcs ?hitbpaics ?hmaxvam ?hmaxvcu ?hminvam ?hminvcu ?hmildes ?hmiltit ?hmildued ?hmilhdocid ?hmilhdoctype ?hmilhdoclan ?hmilhdocurl ?hrbvam ?hrbvcu ?hrbhdocid ?hrbhdoctype ?hrbhdoclan ?hrbhdocurl ?htpstart ?htpend
WHERE {

#Tender information
  ?id a ocds:Tender .
  OPTIONAL { ?id ocds:tenderId ?tenderid } .
  OPTIONAL { ?id dct:title ?tendertitle } .
  OPTIONAL { ?id dct:description ?tenderdescription } .
  OPTIONAL { ?id ocds:tenderStatus ?tenderstatus } .

#Object Property hasDocument
  OPTIONAL { ?id ocds:hasDocument ?hasdoc  .
             ?hasdoc ocds:documentId ?hasdocid  .
             ?hasdoc ocds:documentType ?hasdoctype  .
             ?hasdoc dct:language ?hasdoclan  .
             ?hasdoc schema:URL ?hasdocurl } .

#Object Property hasEnquiryPeriod (none for the time being, only URL)
  OPTIONAL { ?id ocds:hasEnquiryPeriod ?henqperiod  .
             ?henqperiod ocds:startDate ?henqperiodstart  .
             OPTIONAL { ?henqperiod ocds:endDate ?henqperiodend } } .

#Object Property hasItemToBeProcured
  OPTIONAL { ?id ocds:hasItemToBeProcured ?hitbp  .
             ?hitbp ocds:itemId ?hitbpid   .
             OPTIONAL { ?hitbp dct:description ?hitbpdes } .
             ?hitbp ocds:classificatonScheme ?hitbpcs  .
             ?hitbp ocds:hasClassificaton ?hitbphc .
             OPTIONAL { ?hitbp ocds:hasRelatedEnquiry ?hitbphre } .
             OPTIONAL { ?hitbp ocds:additionalItemClassificaton ?hitbpaic } .
             OPTIONAL { ?hitbp ocds:additionalItemClassificatonScheme ?hitbpaics  }} .

#Object Property hasMaxEstimatedValue
  OPTIONAL { ?id ocds:hasMaxEstimatedValue ?hmaxv  .
             ?hmaxv ocds:valueAmount ?hmaxvam  .
            ?hmaxv ocds:valueCurrency ?hmaxvcu } .

#Object Property hasMinEstimatedValue
  OPTIONAL { ?id ocds:hasMinEstimatedValue ?hminv  .
             ?hminv ocds:valueAmount ?hminvam  .
             ?hminv ocds:valueCurrency ?hminvcu } .

#Object Property hasMilestone
  OPTIONAL { ?id ocds:hasMilestone ?hmil  .
             OPTIONAL { ?hmil dct:description ?hmildes} .
             OPTIONAL { ?hmil dct:title ?hmiltit } .
             OPTIONAL { ?hmil ocds:milestoneDueDate ?hmildued } .
             OPTIONAL { ?hmil ocds:hasDocument ?hmilhdoc } .
             ?hmilhdoc ocds:documentId ?hmilhdocid  .
             ?hmilhdoc ocds:documentType ?hmilhdoctype  .
             ?hmilhdoc dct:language ?hmilhdoclan  .
             ?hmilhdoc schema:URL ?hmilhdocurl } .

#Object Property hasReceivedBid
  OPTIONAL { ?id ocds:hasReceivedBid ?hrb  .
             ?hrb ocds:valueAmount ?hrbvam  .
             ?hrb ocds:valueCurrency ?hrbvcu  .
             ?hrb ocds:hasDocument ?hrbhdoc  .
             ?hrbhdoc ocds:documentId ?hrbhdocid  .
             ?hrbhdoc ocds:documentType ?hrbhdoctype  .
             ?hrbhdoc dct:language ?hrbhdoclan  .
             ?hrbhdoc schema:URL ?hrbhdocurl } .

#Object Property hasTenderPeriod
  OPTIONAL { ?id ocds:hasTenderPeriod ?htp  .
             ?htp ocds:startDate ?htpstart  .
             OPTIONAL { ?htp ocds:endDate ?htpend }} .
}
