PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT ?itm ?qdescription ?qclassificationscheme ?qclassification ?qadditclassificationscheme ?qadditclassification
WHERE {
  ?id ocds:hasItemToBeProcured ?itm .
	OPTIONAL { ?itm dct:description ?qdescription } .
	OPTIONAL { ?itm ocds:classificatonScheme ?qclassificationscheme } .
  OPTIONAL { ?itm ocds:hasClassificaton ?qclassification } .
  OPTIONAL { ?itm ocds:additionalItemClassificatonScheme ?qadditclassificationscheme }.
	OPTIONAL { ?itm ocds:hasAdditionalItemClassificaton ?qadditclassification } .
}
