PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT ?hasaw ?qtitle ?qdescription ?qdate ?qstatus
WHERE {
	?id a ocds:ContractingProcess .
  ?id ocds:hasAward ?hasaw .
	OPTIONAL { ?hasaw dct:title ?qtitle } .
	OPTIONAL { ?hasaw dct:description ?qdescription } .
	OPTIONAL { ?hasaw ocds:awardDate ?qdate } .
	OPTIONAL { ?hasaw ocds:awardStatus ?qstatus } .
	FILTER ( isNumeric(?status) = True || regex(?qstatus, ?status, "i") ) .
	FILTER ( isNumeric(?title) = True || regex(?qtitle, ?title, "i") ) .
	FILTER ( isNumeric(?description) = True || regex(?qdescription, ?description, "i") ) .
	FILTER ( isNumeric(?start_dt) = True || ?qdate > ?start_dt ) .
	FILTER ( isNumeric(?end_dt) = True || ?qdate < ?end_dt ) .
}
