PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?hasaw ?qtitle ?qdescription ?qdate ?qstatus
WHERE {
	?id a ocds:ContractingProcess .
  ?id ocds:hasAward ?hasaw .
	OPTIONAL { ?hasaw dct:title ?qtitle } .
	OPTIONAL { ?hasaw dct:description ?qdescription } .
	OPTIONAL { ?hasaw ocds:awardDate ?qdate } .
	OPTIONAL { ?hasaw ocds:awardStatus ?qstatus } .
	FILTER ( ?status = xsd:string("_empty_") || regex(?qstatus, ?status, "i") ) .
	FILTER ( ?title = xsd:string("_empty_") || regex(?qtitle, ?title, "i") ) .
	FILTER ( ?description = xsd:string("_empty_") || regex(?qdescription, ?description, "i") ) .
	FILTER ( ?start_dt = xsd:string("_empty_") || ?qdate > ?start_dt ) .
	FILTER ( ?end_dt = xsd:string("_empty_") || ?qdate < ?end_dt ) .
}
