PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT (?id as ?oid) ?hasaw ?tit ?des ?date ?stat
WHERE {
	?id a ocds:ContractingProcess .
  ?id ocds:hasAward ?hasaw .
	OPTIONAL { ?hasaw dct:title ?tit } .
	OPTIONAL { ?hasaw dct:description ?des } .
	OPTIONAL { ?hasaw ocds:awardDate ?date } .
	OPTIONAL { ?hasaw ocds:awardStatus ?stat } .
}
