PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT ?qid ?qtitle ?qdescription ?qdate ?qstatus WHERE {
	?qid a ocds:Award .
  OPTIONAL { ?qid dct:title ?qtitle } .
  OPTIONAL { ?qid dct:description ?qdescription } .
	OPTIONAL { ?qid ocds:awardDate ?qdate } .
  OPTIONAL { ?qid ocds:awardStatus ?qstatus } .
  FILTER ( regex(?qtitle, ?title, "i") || !isLiteral(?title) ) .
  FILTER ( regex(?qstatus, ?status, "i") || !isLiteral(?status) ) .
  FILTER ( regex(?qdescription, ?description, "i") || !isLiteral(?description) ) .
}
