PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT ?s ?tit ?des ?date ?stat WHERE {
	?s a ocds:Award .
  OPTIONAL { ?s dct:title ?tit } .
  OPTIONAL { ?s dct:description ?des } .
	OPTIONAL { ?s ocds:awardDate ?date } .
  OPTIONAL { ?s ocds:awardStatus ?stat } .
  FILTER ( regex(?stat, ?status, "i") || !isLiteral(?status) ) .
}
