PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>
SELECT ( ?id AS ?oid ) ?tit ?des ?dat ?stat ?startDate ?endDate ?val ?cur ?hdocid ?hdoctype ?hdoclan ?hdocurl ?tid
WHERE {

#Award information
  ?id a ocds:Award .
  OPTIONAL { ?id dct:title ?tit } .
  OPTIONAL { ?id dct:description ?des } .
  OPTIONAL { ?id ocds:awardDate ?dat } .
  OPTIONAL { ?id ocds:awardStatus ?stat } .

#Object Property hasAwardedContractPeriod
  OPTIONAL { ?id ocds:hasAwardedContractPeriod ?cperiod .
  OPTIONAL { ?cperiod ocds:startDate ?startDate .
             ?cperiod ocds:endDate ?endDate }} .

#Object Property hasAwardValue
  OPTIONAL { ?id ocds:hasAwardValue ?valr .
  OPTIONAL { ?valr ocds:ValueAmount ?val .
             ?valr ocds:ValueCurrency ?cur }} .

#Object Property hasDocument
  OPTIONAL { ?id ocds:hasDocument ?hdoc .
  OPTIONAL { ?hdoc ocds:documentId ?hdocid  .
  ?hdoc ocds:documentType ?hdoctype .
  ?hdoc dct:language ?hdoclan .
  ?hdoc schema:URL ?hdocurl }} .

#Object Property isIssuedForTender
  OPTIONAL { ?id ocds:isIssuedForTender ?iift } .
  OPTIONAL { ?iift ocds:tenderId ?tid } .

}
