PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX dbp: <http://dbpedia.org/ontology/>
PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ebg: <http://data.businessgraph.io/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?ss ?supaward ?qlegalname ?qjurisdiction ?qnumemployees ?qawdate WHERE {
  ?s ocds:isSupplierFor ?supaward .
  ?s owl:sameAs ?ss .
  ?ss regorg:legalName ?qlegalname .
  ?ss dbp:jurisdiction ?qjurisdiction .
  ?ss ebg:numberOfEmployees ?qnumemployees .
  ?supaward ocds:awardDate ?qawdate .
  FILTER ( regex(?qjurisdiction, ?jurisdiction, "i") || !isLiteral(?jurisdiction) ) .
  FILTER ( regex(?qlegalname, ?name, "i") || !isLiteral(?name) ) .
#  FILTER ( ?qawdate > "2018-05-23T00:00:00Z"^^xsd:dateTime || !isLiteral(?dateini) )
#  FILTER ( regex(?qawdate > "2014-05-23T10:20:13+05:30"^^xsd:dateTime, ?date, "i") || !isLiteral(?date) ) .
}
