PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX dbp: <http://dbpedia.org/ontology/>
PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?ss ?supaward ?qlegalname ?qjurisdiction WHERE {
  ?s ocds:isSupplierFor ?supaward .
  ?s owl:sameAs ?ss .
  ?ss regorg:legalName ?qlegalname .
  ?ss dbp:jurisdiction ?qjurisdiction .
  FILTER ( regex(?qjurisdiction, ?jurisdiction, "i") || !isLiteral(?jurisdiction) ) .
  FILTER ( regex(?qlegalname, ?name, "i") || !isLiteral(?name) ) .
}
