PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?hasten ?qtitle ?qdescription ?qstatus
WHERE {
  ?id ocds:hasTender ?hasten .
  OPTIONAL { ?hasten dct:title ?qtitle } .
  OPTIONAL { ?hasten dct:description ?qdescription } .
  OPTIONAL { ?hasten ocds:tenderStatus ?qstatus } .
  FILTER ( ?status = xsd:string("_empty_") || regex( ?status, ?status, "i") ) .
  FILTER ( ?title = xsd:string("_empty_") || regex( ?title, ?title, "i") ) .
  FILTER ( ?description = xsd:string("_empty_") || regex( ?description, ?description, "i") ) .
}
