PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT (?id as ?oid) ?hasten ?tit ?des ?stat
WHERE {
	?id a ocds:ContractingProcess .
  OPTIONAL { ?id ocds:hasTender ?hasten } .
  OPTIONAL { ?hasten dct:title ?tit } .
  OPTIONAL { ?hasten dct:description ?des } .
  OPTIONAL { ?hasten ocds:tenderStatus ?stat } .
}
