PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>

SELECT (?id as ?oid) ?hascont ?hascontiid ?hascontstat ?startdate ?enddate
WHERE {
	?id a ocds:ContractingProcess .
	?id ocds:hasContract ?hascont .
  OPTIONAL { ?hascont ocds:hasContractId ?hascontid } .
  OPTIONAL { ?hascont ocds:hasContractStatus ?hascontstat } .
	OPTIONAL { ?hascont ocds:hasContractPeriod ?hcperiod } .
	OPTIONAL { ?hcperiod ocds:startDate ?startdate } .
	OPTIONAL { ?hcperiod ocds:endDate ?enddate } .
}
