PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>

SELECT ?hascont ?startdate ?enddate
WHERE {
	?id ocds:hasContract ?hascont .
	?hascont ocds:hasContractPeriod ?hcp .
	OPTIONAL { ?hcp ocds:startDate ?startdate .
						 ?hcp ocds:endDate ?enddate } .
}
