PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>

SELECT ?hascont ?qstartdate ?qenddate
WHERE {
	?id ocds:hasContract ?hascont .
	?hascont ocds:hasContractPeriod ?hcp .
	OPTIONAL { ?hcp ocds:periodStartDate ?qstartdate .
						 ?hcp ocds:periodEndDate ?qenddate } .
}
