PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX rov: <http://www.w3.org/ns/regorg#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dbp: <http://dbpedia.org/ontology/>
PREFIX bgh: <http://data.businessgraph.io/>
PREFIX schema: <http://schema.org/>

SELECT ?qjurisdiction ?qlegalname ?qstreet ?qpostalcode ?qlocality ?qcountry ?qname ?qemail ?qtelephone ?qurl ?qfax
WHERE {
  ?s a ocds:Organisation .
  ?s ocds:isBuyerFor ?id .
  ?s ocds:legalName ?qlegalname .
  OPTIONAL { ?s owl:sameAs ?sas .
             ?sas rov:legalName ?qlegalname ;
                  dbp:jurisdiction ?qjurisdiction } .
  OPTIONAL { ?s ocds:hasAddress ?haddress .
            OPTIONAL { ?haddress schema:streetAddress ?qstreet .
                       ?haddress schema:postalCode ?qpostalcode .
                       ?haddress schema:addressLocality ?qlocality .
                       ?haddress schema:addressCountry ?qcountry }} .
  OPTIONAL { ?s ocds:hasContactPoint ?hcp .
            OPTIONAL { ?hcp schema:name ?qname .
                       ?hcp schema:email ?qemail .
                       ?hcp schema:telephone ?qtelephone .
                       OPTIONAL { ?hcp schema:URL ?qurl .
                                  ?hcp schema:faxNumber ?qfax }}} .
# So far, no buyer has correspondance with euBG
#  OPTIONAL { ?s owl:sameAs ?sas .
#  OPTIONAL { ?sas rov:legalName ?qname .
#             ?sas dbp:jurisdiction ?qjurisdiction }} .
}
