PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rov: <http://www.w3.org/ns/regorg#>
PREFIX dbp: <http://dbpedia.org/ontology/>
PREFIX schema: <http://schema.org/>

SELECT ?s ?sas ?qlegalname ?qjurisdiction
WHERE {
  ?s a ocds:Organisation .
  ?s ocds:isTendererFor ?id .
  ?s ocds:legalName ?qlegalname .
  OPTIONAL { ?s owl:sameAs ?sas .
             ?sas rov:legalName ?qlegalname ;
                  dbp:jurisdiction ?qjurisdiction } .
  OPTIONAL { ?s ocds:hasAddress ?haddress .
            OPTIONAL { ?haddress schema:streetAddress ?qstreet } .
            OPTIONAL { ?haddress schema:postalCode ?qpostalcode } .
            OPTIONAL { ?haddress schema:addressLocality ?qlocality } .
            OPTIONAL { ?haddress schema:addressCountry ?qcountry }} .
}
