PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>

SELECT (?id as ?oid) ?s ?ln ?ss
WHERE {
	?id a ocds:ContractingProcess .
	?s a ocds:Organisation .
  ?s ocds:playsRoleIn ?id .
	?s ocds:legalName ?ln .
	OPTIONAL { ?s owl:sameAs ?ss } .
}
