PREFIX ocds: <http://data.tbfy.eu/ontology/ocds#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT (?id as ?oid) ?tit ?itm ?lot ?clas ?classch ?enq ?cl1
WHERE {
	?id a ocds:Award .
	OPTIONAL { ?id dct:title ?tit } .
  ?id ocds:hasAwardedItem ?itm .
	OPTIONAL { ?itm a ocds:Item } .
	OPTIONAL { ?itm ocds:isRelatedToLot ?lot } .
	OPTIONAL { ?itm ocds:hasAdditionalItemClassificaton ?clas } .
	OPTIONAL { ?itm ocds:additionalItemClassificatonScheme ?classch } .
	OPTIONAL { ?itm ocds:hasRelatedEnquiry ?enq } .
	OPTIONAL { ?itm ocds:classificatonScheme ?cl1 } .
}
